name: base
channels:
- https://conda.anaconda.org/conda-forge
dependencies:
- libuv=1.44.2
- cfgv=3.3.1
- tblib=1.7.0
- notebook=6.5.4
- alembic=1.11.1
- libpq=15.3
- requests=2.31.0
- libopenblas=0.3.23
- wrapt=1.15.0
- six=1.16.0
- munch=4.0.0
- distlib=0.3.6
- locket=1.0.0
- jsonschema-specifications=2023.6.1
- debugpy=1.6.7
- re2=2023.03.02
- certifi=2023.5.7
- jupyterlab_server=2.23.0
- contourpy=1.1.0
- distributed=2023.3.1
- fasteners=0.17.3
- ipykernel=6.24.0
- gettext=0.21.1
- botocore=1.29.76
- shapely=2.0.1
- libjpeg-turbo=2.1.5.1
- scikit-learn=1.3.0
- backcall=0.2.0
- wcwidth=0.2.6
- libprotobuf=4.23.3
- gdal=3.7.0
- readline=8.2
- aiosignal=1.3.1
- python-tzdata=2023.3
- nbformat=5.9.1
- cartopy=0.21.1
- sniffio=1.3.0
- cycler=0.11.0
- asciitree=0.3.3
- lzo=2.10
- folium=0.14.0
- xorg-xextproto=7.3.0
- ipython_genutils=0.2.0
- asttokens=2.2.1
- jedi=0.18.2
- rasterio=1.3.8
- google-resumable-media=2.5.0
- libthrift=0.18.1
- async_generator=1.10
- pycodestyle=2.10.0
- glog=0.6.0
- libglib=2.76.4
- affine=2.4.0
- libnghttp2=1.52.0
- _libgcc_mutex=0.1
- libev=4.33
- certipy=0.1.3
- tinycss2=1.2.1
- libspatialite=5.0.1
- proj=9.2.1
- tzcode=2023c
- libiconv=1.17
- krb5=1.20.1
- libgcc-ng=13.1.0
- font-ttf-ubuntu=0.83
- libarrow=12.0.1
- cached_property=1.5.2
- pamela=1.0.0
- branca=0.6.0
- pandoc=3.1.3
- typing-extensions=4.7.1
- comm=0.1.3
- fontconfig=2.14.2
- importlib_metadata=6.8.0
- aws-c-compression=0.2.17
- geotiff=1.7.1
- hdf4=4.2.15
- libedit=3.1.20191231
- toolz=0.12.0
- cftime=1.6.2
- ipython=8.14.0
- websocket-client=1.6.1
- jupyterhub-base=4.0.1
- aws-c-common=0.8.23
- mistune=3.0.0
- anyio=3.7.1
- tornado=6.3.2
- numpy=1.25.1
- gflags=2.2.2
- aws-c-http=0.7.10
- colorama=0.4.6
- aws-c-s3=0.3.13
- yarl=1.9.2
- metpy=1.5.1
- importlib-metadata=6.8.0
- cached-property=1.5.2
- pyyaml=6.0
- keyutils=1.6.1
- parso=0.8.3
- libwebp-base=1.3.1
- platformdirs=3.8.1
- kiwisolver=1.4.4
- xorg-libsm=1.2.4
- libblas=3.9.0
- blosc=1.21.4
- poppler=23.05.0
- xarray=2023.6.0
- nspr=4.35
- snuggs=1.4.7
- s2n=1.3.46
- psutil=5.9.5
- pytz=2023.3
- gcsfs=2023.6.0
- liblapack=3.9.0
- s3fs=2023.6.0
- prompt_toolkit=3.0.39
- rdma-core=28.9
- libexpat=2.5.0
- dask-cloudprovider=2022.10.0
- frozenlist=1.3.3
- filelock=3.12.2
- xyzservices=2023.5.0
- xerces-c=3.2.4
- jupyter_telemetry=0.1.0
- rioxarray=0.14.1
- stack_data=0.6.2
- libabseil=20230125.3
- pathspec=0.11.1
- hdf5=1.14.1
- h5py=3.9.0
- nest-asyncio=1.5.6
- xorg-xproto=7.0.31
- jmespath=1.0.1
- libcurl=8.1.2
- pyopenssl=23.2.0
- pycurl=7.45.1
- rfc3986-validator=0.1.1
- pkgutil-resolve-name=1.3.10
- fonts-conda-ecosystem=1
- lerc=4.0.0
- rsa=4.9
- attrs=23.1.0
- send2trash=1.8.2
- ukkonen=1.0.1
- widgetsnbextension=4.0.8
- freexl=1.0.6
- ca-certificates=2023.5.7
- joblib=1.3.0
- xorg-kbproto=1.0.7
- pygments=2.15.1
- importlib_resources=6.0.0
- libxcb=1.15
- jupyterhub=4.0.1
- ld_impl_linux-64=2.40
- decorator=5.1.1
- wheel=0.40.0
- curl=8.1.2
- cytoolz=0.12.0
- soupsieve=2.3.2.post1
- python_abi=3.11
- networkx=3.1
- matplotlib-base=3.7.2
- urllib3=1.26.15
- dask-core=2023.3.1
- tqdm=4.64.1
- lcms2=2.15
- python-json-logger=2.0.7
- libbrotlienc=1.0.9
- libgoogle-cloud=2.12.0
- traitlets=5.9.0
- aiohttp=3.8.4
- idna=3.4
- notebook-shim=0.2.3
- pandocfilters=1.5.0
- libgdal=3.7.0
- pyproj=3.6.0
- threadpoolctl=3.1.0
- flit-core=3.9.0
- boost-cpp=1.78.0
- c-ares=1.19.1
- aws-c-cal=0.6.0
- msgpack-python=1.0.5
- python-dateutil=2.8.2
- openjpeg=2.5.0
- fsspec=2023.6.0
- regionmask=0.9.0
- cryptography=41.0.1
- aws-sdk-cpp=1.10.57
- greenlet=2.0.2
- libspatialindex=1.9.3
- libcrc32c=1.1.2
- libgrpc=1.56.0
- cligj=0.7.2
- executing=1.2.0
- virtualenv=20.23.1
- libbrotlicommon=1.0.9
- babel=2.12.1
- charset-normalizer=3.2.0
- webencodings=0.5.1
- pyzmq=25.1.0
- rpds-py=0.8.10
- libxml2=2.11.4
- geos=3.11.2
- cython=0.29.36
- ipywidgets=8.0.7
- fonts-conda-forge=1
- aws-c-event-stream=0.3.1
- pip=23.1.2
- cachetools=5.3.1
- brotli=1.0.9
- entrypoints=0.4
- ruamel.yaml.clib=0.2.7
- python-fastjsonschema=2.17.1
- nss=3.89
- freetype=2.12.1
- async-timeout=4.0.2
- zeromq=4.3.4
- pooch=1.7.0
- prompt-toolkit=3.0.39
- pyasn1-modules=0.2.7
- zlib=1.2.13
- cfitsio=4.2.0
- referencing=0.29.1
- xorg-renderproto=0.11.1
- watchdog=3.0.0
- font-ttf-inconsolata=3.000
- jupyter_events=0.6.3
- ruamel.yaml=0.17.32
- numcodecs=0.11.0
- ptyprocess=0.7.0
- pandas=2.0.3
- font-ttf-source-code-pro=2.038
- multidict=6.0.4
- configurable-http-proxy=4.5.4
- beautifulsoup4=4.12.2
- json5=0.9.14
- aws-c-io=0.13.28
- exceptiongroup=1.1.2
- pthread-stubs=0.4
- typing_utils=0.1.0
- pyarrow=12.0.1
- tiledb=2.13.2
- jupyter_client=8.3.0
- prometheus_client=0.17.0
- libutf8proc=2.8.0
- pyflakes=3.0.1
- nbconvert=7.6.0
- zarr=2.14.2
- xorg-libx11=1.8.6
- bzip2=1.0.8
- mccabe=0.7.0
- oauthlib=3.2.2
- zstd=1.5.2
- mako=1.2.4
- jupyterlab_pygments=0.2.2
- h5netcdf=1.2.0
- cffi=1.15.1
- google-cloud-core=2.3.3
- libaec=1.0.6
- libsqlite=3.42.0
- pyu2f=0.1.5
- rfc3339-validator=0.1.4
- poppler-data=0.4.12
- matplotlib-inline=0.1.6
- markupsafe=2.1.3
- rtree=1.0.1
- zict=3.0.0
- black=23.3.0
- jupyter-lsp=2.2.0
- aws-c-mqtt=0.8.14
- libnsl=2.0.0
- pure_eval=0.2.2
- tk=8.6.12
- cairo=1.16.0
- sortedcontainers=2.4.0
- python=3.11.4
- openssl=3.1.1
- typing_extensions=4.7.1
- font-ttf-dejavu-sans-mono=2.37
- geopandas=0.13.2
- async-lru=2.0.3
- nbconvert-pandoc=7.6.0
- jupyter_core=5.3.1
- pcre2=10.40
- icu=72.1
- expat=2.5.0
- grpcio=1.56.0
- orc=1.9.0
- dask=2023.3.1
- postgresql=15.3
- pyasn1=0.4.8
- google-crc32c=1.1.2
- libnuma=2.0.16
- libzlib=1.2.13
- libssh2=1.11.0
- libnetcdf=4.9.2
- googleapis-common-protos=1.59.1
- nbclassic=1.0.0
- ncurses=6.4
- pillow=10.0.0
- defusedxml=0.7.1
- flake8=6.0.0
- libstdcxx-ng=13.1.0
- _openmp_mutex=4.5
- nodeenv=1.8.0
- mypy_extensions=1.0.0
- pixman=0.40.0
- setuptools=68.0.0
- gmp=6.2.1
- libsodium=1.0.18
- xz=5.2.6
- fiona=1.9.4
- libzip=1.9.2
- jupyter_server_terminals=0.4.4
- cloudpickle=2.2.1
- pint=0.22
- click-plugins=1.1.1
- google-api-core=2.11.1
- jinja2=3.1.2
- munkres=1.1.4
- mapclassify=2.5.0
- libevent=2.1.12
- pyparsing=3.0.9
- backports.functools_lru_cache=1.6.5
- zipp=3.16.0
- libdeflate=1.18
- libuuid=2.38.1
- overrides=7.3.1
- fonttools=4.40.0
- aws-c-sdkutils=0.1.11
- pexpect=4.8.0
- libtiff=4.5.1
- protobuf=4.23.3
- json-c=0.16
- libkml=1.3.0
- aws-crt-cpp=0.20.3
- jupyterlab_widgets=3.0.8
- xorg-libxext=1.3.4
- libpng=1.6.39
- xorg-libice=1.1.1
- nbclient=0.8.0
- tzdata=2023c
- netcdf4=1.6.4
- scipy=1.11.1
- argon2-cffi-bindings=21.2.0
- pre-commit=3.3.3
- aioitertools=0.11.0
- libgfortran-ng=13.1.0
- aws-c-auth=0.7.0
- aiobotocore=2.5.0
- libbrotlidec=1.0.9
- google-auth=2.21.0
- brotli-bin=1.0.9
- nodejs=18.16.1
- brotlipy=0.7.0
- lz4-c=1.9.4
- pyjwt=2.7.0
- xorg-libxrender=0.9.11
- identify=2.5.24
- librttopo=1.1.0
- partd=1.4.0
- blinker=1.6.2
- xorg-libxau=1.0.11
- sqlite=3.42.0
- giflib=5.2.1
- libffi=3.4.2
- pysocks=1.7.1
- python-dotenv=1.0.0
- pyshp=2.3.1
- backports=1.0
- bokeh=2.4.3
- lz4=4.3.2
- snappy=1.1.10
- argon2-cffi=21.3.0
- libgomp=13.1.0
- libcblas=3.9.0
- jupyter_server=2.7.0
- pycparser=2.21
- kealib=1.5.1
- requests-oauthlib=1.3.1
- nbconvert-core=7.6.0
- jsonschema=4.18.0
- xorg-libxdmcp=1.1.3
- pickleshare=0.7.5
- packaging=23.1
- aws-checksums=0.1.16
- jupyterlab=4.0.2
- libarchive=3.6.2
- click=8.1.4
- terminado=0.17.1
- google-auth-oauthlib=1.0.0
- libgfortran5=13.1.0
- bleach=6.0.0
- tomli=2.0.1
- geopandas-base=0.13.2
- ucx=1.14.1
- google-cloud-storage=2.10.0
- yaml=0.2.5
- sqlalchemy=2.0.18

