name: base
channels:
  - conda-forge
  - default
  - defaults
  - nodefaults
  - javascript
  - pip
platforms:
  - linux-64
dependencies:
  - python>=3.8
  - nodejs>=14
  - notebook
  - jupyterhub
  - jupyterlab
  - bokeh
  - cartopy
  - cython
  - numpy
  - h5py
  - h5netcdf
  - ipywidgets
  - geopandas
  - metpy
  - netcdf4
  - xarray
  - s3fs
  - gcsfs
  - fsspec
  - watchdog
  - flake8
  - black[jupyter]
  - python-dotenv
  - pre-commit
  - click
  - tqdm==4.64.1
  - regionmask==0.9.0
  - dask==2023.3.1
  - dask-cloudprovider
  - zarr==2.14.2
  - rioxarray
